### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by EnriqM** [ahoarau/ethercat-drivers#1]
Excuse me for being a nuisance (again), but the tutorial doesn't work at this point:
```
sudo -s
echo KERNEL==\"EtherCAT[0-9]*\", MODE=\"0664\" > /etc/udev/rules.d/99-EtherCAT.rules
cp etc/init.d/ethercat /etc/init.d/ethercat # to start the master
cp etc/sysconfig/ethercat /etc/sysconfig/ethercat # the config file
exit
```

I can't copy those files because there are not included when downloading with wget. Where can I get them?

**Comment by EnriqM** [comment]
Nevermind, those files are at /opt/etherlab/
I'll close the issue, but it would be nice to include `cd /opt/etherlab` before the copy of those files

**Comment by ahoarau** [comment]
They should be included in the etherlab-1.5.2 folder (the one from wget) ?

**Comment by EnriqM** [comment]
No, they appear once you've installed at 

> /opt/etherlab/

**Comment by ahoarau** [comment]
all right, thanks for the info 👍
